---
- name: Testing andrewrothstein.liquibase
  roles:
  - role: '{{ playbook_dir }}'
  module_defaults:
    group/aws:
      aws_access_key: "test"
      aws_secret_key: "test"
      region: "us-east-1"
      endpoint_url: "http://localhost:4566"
  tasks:
    - name: Executing 'liquibase --version'
      ansible.builtin.command: bash -l -c 'liquibase --version'
      changed_when: false
      register: liquibase_test_output
    - name: Output of 'liquibase --version'
      ansible.builtin.debug:
        msg: '{{ liquibase_test_output.stdout }}'
