---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: bash -l -c 'liquibase --version'
      register: liquibase_test_output
    - debug:
        msg: '{{ liquibase_test_output.stdout }}'
