---
- name: Executing 'javac -version'
  ansible.builtin.command: /usr/local/openjdk-jdk/bin/javac -version
  changed_when: false
  register: openjdk_jdk_test_output
- name: Output (stdout) from 'javac -version'
  ansible.builtin.debug:
    msg: '{{ openjdk_jdk_test_output.stdout }}'
- name: Output (stderr) from 'javac -version'
  ansible.builtin.debug:
    msg: '{{ openjdk_jdk_test_output.stderr }}'
- name: Testing jre executable
  ansible.builtin.import_tasks: test-jre-exe.yml
