---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release | default(ansible_distribution_major_version) }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: Install unarchive ansible module required OS pkgs...
  become: '{{ unarchivedeps_privilege_escalation }}'
  become_user: '{{ unarchivedeps_privilege_escalation_user }}'
  ansible.builtin.package:
    name: '{{ unarchivedeps_all_pkgs + unarchivedeps_tar_pkgs + unarchivedeps_xz_pkgs }}'
    state: present
