name: Deploy AWS infra and test the role
on:
  pull_request:
    branches:
      - main

jobs:
  test-ansible-role:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Start & Configure LocalStack
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          pip install localstack awscli-local
          docker pull localstack/localstack-pro
          localstack start -d
          echo "Waiting for LocalStack startup..."
          localstack wait -t 30
          echo "Startup complete"

      - name: Create a Key Pair
        run: |
          awslocal ec2 create-key-pair --key-name ansible-ec2-key --query 'KeyMaterial' --output text > key.pem
          chmod 400 key.pem

      - name: Run ec2 instance
        run: |
          JSON_DATA=$(awslocal ec2 run-instances --image-id ami-ff0fea8310f3 --count 1 --instance-type t3.nano --key-name ansible-ec2-key)
          localstack logs
          echo "PUBLIC_IP=$(awslocal ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)" >> $GITHUB_ENV
          echo $PUBLIC_IP

      - name: Create Inventory File
        run: |
          echo "[all]" > inventory.ini
          echo "ansible_host=127.0.0.1" >> inventory.ini
          echo "host_key_checking=False" >> inventory.ini
          echo "connection=local" >> inventory.ini
          cat inventory.ini

      - name: Deploy Playbook
        run: |
          ansible-playbook -i inventory.ini playbook.yml
