name: Deploy AWS infra and test the role
on:
  pull_request:
    branches:
      - main

jobs:
  test-ansible-role:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Start & Configure LocalStack
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          pip install localstack awscli-local
          docker pull localstack/localstack-pro
          localstack start -d
          echo "Waiting for LocalStack startup..."
          localstack wait -t 30
          echo "Startup complete"

      - name: Create a Key Pair
        run: |
          awslocal ec2 create-key-pair --key-name ansible-ec2-key --query 'KeyMaterial' --output text | tee key.pem
          chmod 400 key.pem

      - name: Add rules to the security group
        run: |
          SG_YAML=$(awslocal ec2 authorize-security-group-ingress --group-id default --protocol tcp --port 22 --cidr 0.0.0.0/0)
          echo "SG_ID=$(echo \"$INPUT_YAML\" | grep -A 1 "SecurityGroups:" | grep "GroupId:" | awk '{print $2}')" >> $GITHUB_ENV

      - name: Run ec2 instance
        run: |
          awslocal ec2 run-instances --image-id ami-ff0fea8310f3 --count 1 --instance-type t3.nano --key-name ansible-ec2-key --security-group-ids $env.SG_ID

      - name: Deploy Playbook
        run: |
          ansible-playbook -i inventory -u ubuntu playbook.yml
